apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: cp.icr.io/cp/manage/extension-icd:9.1.53-amd64@sha256:adbd03c31edd245022bc5bfc83b64838c0ab0864e51a5fb39a6717541e919b55
