apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: quay.io/opendatahub/odh-model-controller:odh-v2.32
  - name: quay.io/opendatahub/data-science-pipelines-operator:odh-v2.32
  - name: quay.io/opendatahub/kserve-controller:odh-v2.32
  - name: quay.io/opendatahub/kserve-storage-initializer:odh-v2.32
  - name: quay.io/opendatahub/opendatahub-operator:odh-v2.32
