apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-facilities-operator-bundle@sha256:cbe70d7cb6beb838838244d1c6ae6314aca9082f96cef865ec96048203640add
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/ibm-mas-facilities-ws:9.2.0-pre.daily-2026-05-04@sha256:0659fa6a11b979a635f030a85ebbdf787d37bfb9ccf336c02e0678bfab03c751
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/datainit:DEV_118@sha256:8b88eb393a7bdc34843260e1862455dde6fcb7aa5deada0e53188d362627a559
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/platform:DEV_403665@sha256:6788109b9a8276fcad22d672c4d803b69e7fbeda98710efe798503afc1afe184
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-facilities:9.2.0-pre.daily-2026-05-04@sha256:42c0480026f62f95713b5cce1dbc3eec84b105c02bcf8b9464a9594bf33cb283
