apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-facilities-operator-bundle@sha256:bc420df30fe0f3611eb9141c18320e95149e7ae2ab8750301c889f689132a551
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/ibm-mas-facilities-ws:9.2.0-pre.daily-2026-05-04@sha256:febcd12d6d32e67cf60b91259e210ed0aaf5e0a82be29d056a7dcad2775690f8
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/datainit:DAILY_117@sha256:0b2a5abf466b739d86b9d332fada171f7e1cd8c2e0012ab031b4bd2b41293aff
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/platform:DEV_403665@sha256:6788109b9a8276fcad22d672c4d803b69e7fbeda98710efe798503afc1afe184
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-facilities:9.2.0-pre.daily-2026-05-04@sha256:2a7668fcb044e417fca5b151926563df0b6b2a319992ab120fad0d11a29f5e9e
