apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-facilities-operator-bundle@sha256:d7f54f54969eb4aed2076b2d0036dddef9c65b36c9bde81130cb258d25396673
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/ibm-mas-facilities-ws:9.2.0-pre.daily-2026-05-05@sha256:22f97e8a03a1463db593c0d571786e498c928b4da0189837dd2863b372095517
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/datainit:DEV_121@sha256:e6e64536f91a387cd44718f0f2d68be9f6f9c8601e5e3bc2b5fe5ef15afa0ffa
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/facilities/platform:DEV_403689@sha256:e873438e6f7ebc8c6b25e0be1b46ed74d60da71049188435b994357b4f4e59e1
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-facilities:9.2.0-pre.daily-2026-05-05@sha256:941228066fab45c5e5b158f0508a6f80ac32b81b0b930150d9cbc7e39da589c0
