case_name: ibm-analyticsengine
case_version: 5.4.0
charts:
- name: analyticsengine
  version: 5.4.0
- name: analyticsengine-cluster-scoped
  version: 5.4.0
- name: analyticsengine-migration
  version: 0.0.0
helm_repo: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
