apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-maximo-operator-catalog:v9-260305-ppc64le@sha256:5defbc1701537d0f5dcb60de1cf43fe687dde1d0d10074b21e82fbc222aa81de
