apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-maximo-operator-catalog:v9-260305-amd64@sha256:192fdb38b135b828916fba8d77c6bee10e6c4f33b4cfd252576ca120e442784b
