apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibm-maximo-operator-catalog:v9-260226-s390x@sha256:9a9eaa1d36b15dfc16a91276edaf2ff63d2a84d7cdede799592e1bc6ebf92546
