apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: cp.icr.io/cp/manage/extension-icd:9.2.45-amd64@sha256:356832aba178ee7093e6efda37e0cc5d66024dc14fe5c1955d88848ac477fe8d
