apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/manage/extension-icd:9.2.31-amd64@sha256:3a9875d42b77f56a25382ef0f56eb179c2108cbd3d76e0a8a1e023a918004c50
