apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-sls-operator-bundle@sha256:e6034e49e9cdf5e4142a96b44c703eee18c4dcf9794902d69f2e26f714d76de5
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-sls/api-licensing:7.6.4-pre.onprem-peak-s390x@sha256:ec6c8d121e5f5c78f43bbd67457dc9870af46b59faf355e590711a200dab91cd
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-sls:3.12.9-pre.onprem-peak-s390x@sha256:67de6f253e6bd1bba419356d6b293291b97bec25818414fe51d4c2af5daa37bc
