case_name: ibm-cognos-analytics-prod
case_version: 29.1.0
charts:
- name: cognos-analytics
  version: 29.1.0
- name: cognos-analytics-cluster-scoped
  version: 29.1.0
- name: cognos-analytics-migration
  version: 29.1.0
helm_repo: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
