apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/manage/extension-icd:9.2.32-s390x@sha256:75ca253677ed3e321e88202c7390a787a30ada3be0d60aff18f20cbb751337c0
