apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: cp.icr.io/cp/manage/extension-icd:9.2.49-s390x@sha256:4df49a123faec7bdc4094e2c454af659bd02ece04f7afe31aa4270b1474ca907
