apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/manage/extension-icd:9.2.24-s390x@sha256:94b7ed2308865bbc859423a578880487dfae0003a7e5c99a4cb6c505717b739e
