apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-predict-operator-bundle@sha256:c7ab4b085b606fb05bbca210d164b6f6239b058b0b3fa87ddfa2ff2701143c58
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/mas/kubectl:5.0.20@sha256:61bc875d64a472380e690ea485300b35c0491aaf68368664831a2a8db8161bbe
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/predict/ibm-mas-predict-ws:9.0.15-pre.maint90xdev@sha256:42e7caa4b1984fdba3af3139561dc944a5ab8a22c30bba7413775c2dc2dfd100
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/predict/explainability:1.7.12@sha256:e3578ea0c0616a0bf62714c1da1d933df35a53c7b805f17cedc74307cce20fba
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/predict/mat-service:1.5.3@sha256:82b8c8d7e6fd4fb05d50513fe9141217264aba6fa20dce1fb9a3af12b2153080
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/predict/predict-api:6.0.19@sha256:ff35b24e480fcb097f81b7fa1e210866e15fd5aa7b5362663a0c2674c704bdfc
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-mas-predict:9.0.15-pre.maint90xdev@sha256:67a6713dffe4d5f5be99daaf48813e44f371da9282f102b4193f5b3692be0c06
