#!/usr/bin/env python3
"""
Digest lookup script for IBM CASE packages.
Searches for a specific image digest in the images.csv file generated by oc ibm-pak.
"""

import argparse
import csv
import subprocess
import sys
import os


def run_command(cmd: list) -> int:
    """
    Execute a command and handle output/errors.

    Args:
        cmd: List of command arguments to execute

    Returns:
        0 on success, 1 on failure
    """
    print(f"Executing: {' '.join(cmd)}")

    try:
        result = subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True
        )
        print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        return 0

    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}", file=sys.stderr)
        if e.stdout:
            print(e.stdout)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        return 1
    except FileNotFoundError:
        print("Error: 'oc' command not found. Please ensure OpenShift CLI is installed.", file=sys.stderr)
        return 1


def lookup_digest(case_name: str, case_version: str, lookup_digest: str) -> int:
    """
    Look up a digest in the images.csv file for a given CASE package.

    Args:
        case_name: Name of the CASE package (e.g., ibm-db2uoperator)
        case_version: Version of the CASE package
        lookup_digest: Digest to search for (with or without 'sha256:' prefix)

    Returns:
        0 if digest found, 1 if not found or error occurred
    """
    # Normalize the lookup digest - ensure it has sha256: prefix
    if not lookup_digest.startswith("sha256:"):
        lookup_digest = f"sha256:{lookup_digest}"

    # Convert version format for oc ibm-pak command
    # For pre-release versions: "9.2.0-pre.stable_9887" -> "9.2.0-pre.stable.9887"
    case_version_for_pak = case_version.replace('_', '.')

    # Construct path to images.csv
    images_csv_path = os.path.expanduser(
        f"~/.ibm-pak/data/cases/{case_name}/{case_version_for_pak}/{case_name}-{case_version_for_pak}-images.csv"
    )

    # Check if images.csv exists, if not run oc ibm-pak get
    if not os.path.exists(images_csv_path):
        print(f"Images CSV not found at {images_csv_path}")
        print(f"Running oc ibm-pak get to download CASE package...")

        cmd = [
            "oc", "ibm-pak", "get", case_name,
            "--version", case_version_for_pak,
            "--skip-dependencies"
        ]

        result = run_command(cmd)
        if result != 0:
            print(f"Failed to download CASE package {case_name} version {case_version}", file=sys.stderr)
            return 1

        # Verify the file was created
        if not os.path.exists(images_csv_path):
            print(f"Error: Images CSV still not found after download: {images_csv_path}", file=sys.stderr)
            return 1

    print(f"\nSearching for digest: {lookup_digest}")
    print(f"In file: {images_csv_path}\n")

    # Search through the CSV file
    found = False
    matching_images = []

    try:
        with open(images_csv_path, 'r') as file:
            reader = csv.reader(file)
            header = next(reader)  # Skip the header row

            for row in reader:
                # CSV format: registry,image_name,tag,digest,mtype,os,arch,variant,insecure,digest_source,image_type,groups
                if len(row) < 4:
                    continue

                registry = row[0]
                image_name = row[1]
                tag = row[2]
                digest = row[3]

                # Check if this row contains the digest we're looking for
                if digest == lookup_digest:
                    found = True
                    full_image = f"{registry}/{image_name}:{tag}@{digest}"
                    matching_images.append(full_image)

    except FileNotFoundError:
        print(f"Error: Could not open images CSV file: {images_csv_path}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Error reading CSV file: {e}", file=sys.stderr)
        return 1

    # Print results
    print("=" * 80)
    if found:
        print(f"✓ DIGEST FOUND")
        print(f"\nThe digest '{lookup_digest}' was found in {len(matching_images)} image(s):")
        for image in matching_images:
            print(f"  - {image}")
        print("=" * 80)
        return 0
    else:
        print(f"✗ DIGEST NOT FOUND")
        print(f"\nThe digest '{lookup_digest}' was NOT found in the CASE package.")
        print(f"CASE: {case_name}")
        print(f"Version: {case_version}")
        print("=" * 80)
        return 1


def parse_arguments():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description='Look up an image digest in IBM CASE package images.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --case ibm-db2uoperator --version "7.1.3+20250318.142355.13789" --lookup "3d1101e38d70df7948fca7e8dab958e20e4b43acc10b3ba0de1a00beba6036a0"
  %(prog)s --case ibm-mas --version "9.1.0" --lookup "sha256:abc123..."
        """
    )

    parser.add_argument('--case', type=str, required=True,
                        help='CASE package name (e.g., ibm-db2uoperator)')
    parser.add_argument('--version', type=str, required=True,
                        help='CASE package version (e.g., 7.1.3+20250318.142355.13789)')
    parser.add_argument('--lookup', type=str, required=True,
                        help='Image digest to search for (with or without sha256: prefix)')

    return parser.parse_args()


def main():
    """Main entry point for the script."""
    args = parse_arguments()

    result = lookup_digest(args.case, args.version, args.lookup)
    sys.exit(result)


if __name__ == "__main__":
    main()
