case_name: ibm-redis-cp
case_version: 1.3.1
charts:
- name: ibm-redis-cp
  version: 1.3.1
- name: ibm-redis-cp-cluster-scoped
  version: 1.3.1
- name: ibm-redis-cp-migration
  version: 0.0.0
helm_repo: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
