apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  additionalImages:
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-truststore-mgr-operator-bundle@sha256:69590bc6f93669bca2920e86a16be48b4e5ebedebfd29b8575e6da9ad2404b57
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-truststore-mgr/worker:1.7.7-pre.ren-9225b91676-amd64@sha256:3d40c3d2d6d03e2936253b2407c627e181e8376340842130b392c8297edda601
  - name: docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/cpopen/ibm-truststore-mgr:1.7.7-pre.ren-9225b91676-amd64@sha256:70bfb50a2a9be3c698b62773178828aef4ac781f28fc92f2d170e11596529322
