case_name: ibm-wsl
case_version: 12.1.0
charts:
- name: ws
  version: 12.1.0
- name: ws-cluster-scoped
  version: 12.1.0
- name: ws-migration
  version: 0.0.0
helm_repo: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
